//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int id { get; set; }
        public Nullable<int> Book_id { get; set; }
        public Nullable<System.DateTime> Borrow_Date { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<int> S_id { get; set; }
        public Nullable<int> L_id { get; set; }
    
        public virtual Librarian Librarian { get; set; }
        public virtual Student Student { get; set; }
    }
}
